workspaces:
  - name: '1'
    bind_to_monitor: 0
  - name: '2'
    bind_to_monitor: 0
  - name: '3'
    bind_to_monitor: 0
  - name: '4'
    bind_to_monitor: 0
  - name: '5'
    bind_to_monitor: 0
  - name: '6'
    bind_to_monitor: 0
  - name: '7'
    bind_to_monitor: 0
  - name: '8'
    bind_to_monitor: 0
  - name: '9'
    bind_to_monitor: 0
  - name: '10'
    bind_to_monitor: 0

